version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextapp

  nextapp:
    image: node:latest
    container_name: nextapp
    volumes:
      - ./app:/app/
    working_dir: /app/
    entrypoint: /app/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./docker/mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - "mysql:mysql"
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin:/var/www/html/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql