version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nestapp
      - nextapp

  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  
  nextapp:
    container_name: nextapp
    build: ./front
    volumes:
      - ./front:/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nestapp

  nestapp:
    build: ./back
    container_name: nestapp
    volumes:
      - ./back:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgresql
    restart: always

  phppgadmin:
    container_name: phppgadmin
    image: docker.io/bitnami/phppgadmin:7
    environment:
      - DATABASE_HOST=postgresql
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - postgresql